


name: exam_prep_tool
version: 1.0.2+4
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  velocity_x: ^4.1.2
  flutter_switch: ^0.3.0
  image_picker:
  shared_preferences:
  syncfusion_flutter_pdfviewer:
  # syncfusion_flutter_pdfviewer:
  readmore:
  razorpay_web:
 
  intl:
  carousel_slider: ^4.2.1
  flutter_html:
  js:
  # video_player_win:
  msix: ^3.16.7
  fvp: ^0.22.0
  video_player:
  media_kit: ^1.1.10+1
  media_kit_video: any
  media_kit_libs_video: any

  flutter:
    sdk: flutter
  flutter_fadein: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  hexcolor: ^3.0.1
  shimmer: ^3.0.0
  retrofit:
  
  firebase_messaging:
  screen_protector: ^1.4.2
  http: ^1.2.0
  dio:
  url_strategy:
  encrypt: ^5.0.0
  share_plus: ^9.0.0
  # flutter_inappwebview: ^6.0.0
  # webview_flutter: ^4.0.0
  window_manager: ^0.3.9
  # desktop_webview_window: ^0.2.3
  webview_windows: ^0.4.0
  uni_links: ^0.5.1
  dotted_border: ^2.1.0
  
  
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  retrofit_generator: 8.1.2
  flutter_gen_runner: any
  build_runner:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo_256_256.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/logo_256_256.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/logo_256_256.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

msix_config:
  display_name: Ept
  publisher_display_name: EXAMPREPTOOL
  identity_name: EXAMPREPTOOL.Ept
  publisher: CN=8A0A7BCF-FE9D-4C6A-8512-32694D0B47DF
  logo_path: images/logo_256_256.png
  msix_version: 1.0.3.0 # Incremented version
  store: true

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/razorpay_checkout.html
  fonts:
    - family: Poppins
      fonts:
        - asset: images/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: images/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: images/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: images/fonts/PoppinsBold.ttf
          weight: 700
        - asset: images/fonts/PoppinsExtraBold.ttf
          weight: 800
        - asset: images/fonts/PoppinsLight.ttf